const STATE_VOTING_PAGE_SLUGS: Record<string, string> = {
  AL: "alabama",
  AK: "alaska",
  AS: "american-samoa",
  AZ: "arizona",
  AR: "arkansas",
  CA: "california",
  CO: "colorado",
  CT: "connecticut",
  DC: "district-of-columbia",
  DE: "delaware",
  FL: "florida",
  GA: "georgia",
  GU: "guam",
  HI: "hawaii",
  IA: "iowa",
  ID: "idaho",
  IL: "illinois",
  IN: "indiana",
  KS: "kansas",
  KY: "kentucky",
  LA: "louisiana",
  MA: "massachusetts",
  MD: "maryland",
  ME: "maine",
  MI: "michigan",
  MN: "minnesota",
  MO: "missouri",
  MP: "northern-mariana-islands",
  MS: "mississippi",
  MT: "montana",
  NC: "north-carolina",
  ND: "north-dakota",
  NE: "nebraska",
  NH: "new-hampshire",
  NJ: "new-jersey",
  NM: "new-mexico",
  NV: "nevada",
  NY: "new-york",
  OH: "ohio",
  OK: "oklahoma",
  OR: "oregon",
  PA: "pennsylvania",
  PR: "puerto-rico",
  RI: "rhode-island",
  SC: "south-carolina",
  SD: "south-dakota",
  TN: "tennessee",
  TX: "texas",
  UT: "utah",
  VA: "virginia",
  VI: "u-s-virgin-islands",
  VT: "vermont",
  WA: "washington",
  WI: "wisconsin",
  WV: "west-virginia",
  WY: "wyoming",
};

const STATE_NAMES: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AS: "American Samoa",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DC: "District of Columbia",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  GU: "Guam",
  HI: "Hawaii",
  IA: "Iowa",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  MA: "Massachusetts",
  MD: "Maryland",
  ME: "Maine",
  MI: "Michigan",
  MN: "Minnesota",
  MO: "Missouri",
  MP: "Northern Mariana Islands",
  MS: "Mississippi",
  MT: "Montana",
  NC: "North Carolina",
  ND: "North Dakota",
  NE: "Nebraska",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NV: "Nevada",
  NY: "New York",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VA: "Virginia",
  VI: "U.S. Virgin Islands",
  VT: "Vermont",
  WA: "Washington",
  WI: "Wisconsin",
  WV: "West Virginia",
  WY: "Wyoming",
};

export function getStateVotingPage(
  stateCode: string | null | undefined
): { label: string; url: string } | null {
  if (!stateCode) return null;

  const normalized = stateCode.trim().toUpperCase();
  const slug = STATE_VOTING_PAGE_SLUGS[normalized];
  const stateName = STATE_NAMES[normalized];

  if (!slug || !stateName) {
    return null;
  }

  return {
    label: `${stateName} voting page (Vote.gov)`,
    url: `https://vote.gov/register/${slug}/`,
  };
}
